package org.emerge.demo.fluidlab.chem

/**
 * The saturation curve: where a fluid holds liquid and vapour side by side, and at what pressure.
 *
 * [reducedPressure] on its own has a defect that is fatal to an explicit solver, and it is not a
 * rounding problem or a tuning problem — it is the equation being honest about something the grid
 * cannot represent. Over a wide band of densities the van der Waals isotherm *falls* as the fluid
 * is compressed, so `dP/dρ` is negative and the speed of sound `√(dP/dρ)` is imaginary. A
 * disturbance there does not oscillate, it grows exponentially, and it grows *faster* the finer
 * the grid. No timestep stabilises it. That band runs from about `ρr = 0.24` to `ρr = 2.06` for
 * water at room temperature, which is very nearly the whole distance between vapour and liquid —
 * and every cell straddling the surface of a pool sits in it, because a cell holding half a pool
 * holds a density halfway between the two phases.
 *
 * The resolution is the one real fluids use: **the cell does not sit at that mean density, it
 * separates.** A tile holding "half a pool" is not a uniform fluid of intermediate density; it is
 * some liquid at [saturatedLiquidDensity] and some vapour at [saturatedVapourDensity], and the
 * pressure it reports is neither branch's but the pressure the two coexist at — [saturationPressure],
 * the same value at every density across the band. So the falling stretch is replaced by a flat
 * one, `dP/dρ` becomes **zero rather than negative**, and the cell is neutrally stable instead of
 * explosively unstable.
 *
 * That flat line is not an approximation of the equation, it *is* what the equation predicts once
 * a cell is allowed to hold two phases at once. It is the Maxwell construction, and it is fixed by
 * a condition with no freedom in it: the two phases must have equal Gibbs free energy, which comes
 * to `∫v dP = 0` along the isotherm between them — the equal-area rule that [SATURATION_PRESSURE]
 * is built from and `SaturationTest` re-derives rather than trusts.
 *
 * ### Why one table serves every fluid
 *
 * Because [reducedPressure] is in reduced units, the saturation curve is a function of reduced
 * temperature **and nothing else**. Water, nitrogen and carbon dioxide do not get a table each;
 * they read the same one at different places, exactly as they share the same isotherm. This is the
 * law of corresponding states again, and it is the reason a phase transition still cannot be
 * authored per species.
 */

/** Samples across `Tr = 0 .. 1`. Even spacing; index 0 is absolute zero, [N] − 1 the critical point. */
private const val N = 65

/**
 * Reduced saturation pressure at each sample, in [SCALE].
 *
 * Generated by solving the equal-area condition to convergence at each sample and rounding to
 * [SCALE], not fitted or hand-tuned. `SaturationTest` re-solves the condition and checks these
 * values against it, so a corrupted entry is caught rather than believed.
 *
 * The leading zeros are real rather than missing data: below about `Tr = 0.16` the true saturation
 * pressure is smaller than [SCALE] can represent — under `1e-8` of critical — and zero is the
 * correct rendering of it. A liquid that cold has no measurable vapour pressure and does not
 * evaporate, which is what the zero goes on to make happen.
 */
private val SATURATION_PRESSURE = longArrayOf(
    0L, 0L, 0L, 0L,
    0L, 0L, 0L, 0L,
    0L, 0L, 1L, 8L,
    39L, 154L, 502L, 1396L,
    3417L, 7519L, 15152L, 28350L,
    49805L, 82907L, 131745L, 201079L,
    296292L, 423319L, 588562L, 798807L,
    1061136L, 1382846L, 1771370L, 2234208L,
    2778870L, 3412820L, 4143437L, 4977975L,
    5923538L, 6987054L, 8175261L, 9494693L,
    10951672L, 12552302L, 14302468L, 16207834L,
    18273848L, 20505739L, 22908528L, 25487029L,
    28245855L, 31189425L, 34321970L, 37647541L,
    41170014L, 44893097L, 48820339L, 52955133L,
    57300725L, 61860222L, 66636593L, 71632681L,
    76851202L, 82294760L, 87965841L, 93866828L,
    100000000L,
)

/**
 * Reduced density of the liquid that coexists at [SATURATION_PRESSURE], in [SCALE] — the dense
 * branch of the saturation dome.
 *
 * Runs from [CLOSE_PACKED] at absolute zero down to critical density at the critical point, where
 * it meets [SATURATED_VAPOUR_DENSITY] and the two phases stop being distinguishable. That meeting
 * is why the dome closes and why there is no liquid above `Tc`.
 */
private val SATURATED_LIQUID_DENSITY = longArrayOf(
    300000000L, 300000000L, 300000000L, 300000000L,
    294337567L, 292886902L, 291421356L, 289940464L,
    288443731L, 286930639L, 285400640L, 283853153L,
    282287566L, 280703228L, 279099450L, 277475503L,
    275830614L, 274163965L, 272474695L, 270761895L,
    269024610L, 267261837L, 265472527L, 263655579L,
    261809842L, 259934109L, 258027117L, 256087539L,
    254113978L, 252104965L, 250058945L, 247974273L,
    245849200L, 243681864L, 241470273L, 239212291L,
    236905619L, 234547775L, 232136066L, 229667562L,
    227139061L, 224547046L, 221887639L, 219156542L,
    216348966L, 213459543L, 210482219L, 207410120L,
    204235380L, 200948925L, 197540181L, 193996703L,
    190303658L, 186443121L, 182393067L, 178125910L,
    173606275L, 168787482L, 163605661L, 157969209L,
    151738075L, 144677415L, 136331151L, 125526788L,
    100000000L,
)

/**
 * Reduced density of the vapour that coexists at [SATURATION_PRESSURE], in [SCALE] — the sparse
 * branch of the dome, and the density at which a gas becomes unable to hold any more of itself and
 * starts to condense.
 *
 * The zeros at the cold end carry the same meaning as in [SATURATION_PRESSURE], and one further
 * consequence: where this reads zero, any amount of the species at all is at or above saturation,
 * so a trace of it in a cold cell condenses completely rather than lingering as a vapour. That is
 * the right behaviour, and it is what makes a cold surface collect frost rather than ignore it.
 */
private val SATURATED_VAPOUR_DENSITY = longArrayOf(
    0L, 0L, 0L, 0L,
    0L, 0L, 0L, 0L,
    0L, 0L, 3L, 17L,
    78L, 284L, 860L, 2235L,
    5126L, 10620L, 20217L, 35854L,
    59883L, 95031L, 144334L, 211067L,
    298671L, 410681L, 550673L, 722217L,
    928846L, 1174033L, 1461185L, 1793642L,
    2174681L, 2607535L, 3095411L, 3641514L,
    4249071L, 4921370L, 5661789L, 6473839L,
    7361208L, 8327810L, 9377843L, 10515859L,
    11746837L, 13076281L, 14510333L, 16055915L,
    17720901L, 19514343L, 21446762L, 23530529L,
    25780379L, 28214121L, 30853649L, 33726405L,
    36867607L, 40323768L, 44158587L, 48463484L,
    53378325L, 59137764L, 66197686L, 75730388L,
    100000000L,
)

/**
 * Linear interpolation into one of the saturation tables at reduced temperature [temperatureR].
 *
 * Linear is enough, but the error is not uniform and it is worth knowing where it lives — all of
 * it is measured by `SaturationTest`, which re-solves the curve rather than trusting these numbers.
 *
 * - **Saturation pressure: within 1%** over the range any of these fluids is not a solid, worst
 *   around `Tr = 0.4` where the curve is most nearly exponential and a chord fits it least well.
 *   This is the one the solver's stability rests on.
 * - **The two densities: within 8%**, concentrated entirely in the last few knots. The dome closes
 *   as `√(1 − Tr)`, so both branches reach the critical point with infinite slope, and no table
 *   sampled evenly in `Tr` can follow a cusp. Sampling evenly in `√(1 − Tr)` instead would remove
 *   it, at the cost of a square root on this path; not done, because nothing in the vessel runs
 *   near a critical point.
 * - **Below `Tr ≈ 0.35** the values are exponentially small and the table overestimates them by
 *   tens of percent. Immaterial: every fluid here is frozen solid by then, and there is no solid
 *   phase in this model, so that stretch describes a substance that does not exist.
 *
 * Refining [N] moves the first two with a known exchange rate — the error is second order, so it
 * falls fourfold per doubling — if a use ever needs it to.
 */
private fun sample(table: LongArray, temperatureR: Long): Long {
    val position = temperatureR * (N - 1)
    val index = (position / SCALE).toInt()
    if (index >= N - 1) return table[N - 1]
    val fraction = position % SCALE
    val low = table[index]
    return low + (table[index + 1] - low) * fraction / SCALE
}

/**
 * The pressure at which liquid and vapour of a fluid at reduced temperature [temperatureR] sit in
 * equilibrium — its **vapour pressure**, in [SCALE].
 *
 * This is the boiling curve, and it is the answer to the question the equation of state
 * deliberately refuses to answer directly: a fluid boils where this exceeds the pressure pressing
 * on it. A pot of water on a mountain and the same pot at sea level read the same curve here and
 * boil at different temperatures, because what changed was the other side of the comparison.
 *
 * Null above the critical temperature, where liquid and vapour are not different things and there
 * is nothing to be in equilibrium *between*.
 */
fun saturationPressure(temperatureR: Long): Long? =
    if (temperatureR >= SCALE) null else sample(SATURATION_PRESSURE, temperatureR)

/** Reduced density of saturated liquid at [temperatureR], or null above the critical point. */
fun saturatedLiquidDensity(temperatureR: Long): Long? =
    if (temperatureR >= SCALE) null else sample(SATURATED_LIQUID_DENSITY, temperatureR)

/** Reduced density of saturated vapour at [temperatureR], or null above the critical point. */
fun saturatedVapourDensity(temperatureR: Long): Long? =
    if (temperatureR >= SCALE) null else sample(SATURATED_VAPOUR_DENSITY, temperatureR)

/**
 * What fraction of a cell's volume is liquid, in [SCALE], for a cell inside the saturation dome —
 * the **lever rule**.
 *
 * A cell at mean density `ρ` between the two branches holds liquid at `ρl` and vapour at `ρv` in
 * whatever proportion averages to `ρ`, which fixes the split with no freedom left over:
 * `f = (ρ − ρv) / (ρl − ρv)`. Zero at the vapour branch, one at the liquid branch, and sweeping
 * from one to the other *is* boiling — a cell does not jump between phases, it crosses the dome,
 * and how far across it has got is this number.
 *
 * Returns 0 below the dome, `SCALE` above it, and null above the critical temperature.
 */
/**
 * How much of a cell [species] fills as *liquid*, in [SCALE] — the share of the room that is taken
 * and is no longer available to anything else.
 *
 * **A liquid displaces the gas above it, and until this existed nothing here said so.** Every
 * species shared the whole cell, so a pool of water contributed its vapour pressure *on top of* an
 * undisturbed atmosphere of nitrogen, which put the tile holding it at 1.66 atm against neighbours
 * at 1.00 and blew it apart within a handful of ticks — mass conserved, no instability, the pool
 * simply pushed itself across the room. That looked like the stiffness problem returning and is
 * something else entirely: a pool cannot sit still until the nitrogen has somewhere to not be.
 *
 * Returns 0 for a species that is not condensing, which is every species in the vessel today.
 */
fun liquidVolumeFraction(grams: Long, species: Species, volume: Int, full: Int, kelvin: Int): Long {
    val densityR = reducedDensity(grams, species, volume, full) ?: return 0L
    val temperatureR = reducedTemperature(kelvin, species) ?: return 0L
    return liquidFraction(densityR, temperatureR) ?: 0L
}

/**
 * How many of a cell's [grams] of [species] are present as **vapour** — the rest being liquid.
 *
 * The lever rule again, read as a mass rather than as a volume: the cell holds `1 − f` of its room
 * at [saturatedVapourDensity], and that volume times that density is this. Returns all of [grams]
 * for a species that is not condensing, which is every species in the vessel today.
 *
 * This exists because **the two phases are not the same substance as far as transport is
 * concerned.** Fick's law describes a mixture spreading through itself, and a pool sitting under an
 * atmosphere is not a mixture — it is two phases with an interface. Differencing concentration
 * across that interface makes the pool read as an infinitely steep gradient and drift dissolves it,
 * which is measurably what was happening: a saturated pool shed 76% of itself in twenty ticks, and
 * excluding its liquid from drift leaves it holding 87%.
 */
fun vapourGrams(grams: Long, species: Species, volume: Int, full: Int, kelvin: Int): Long {
    if (grams <= 0L) return grams
    val temperatureR = reducedTemperature(kelvin, species) ?: return grams
    val vapourR = saturatedVapourDensity(temperatureR) ?: return grams
    val liquidShare = liquidVolumeFraction(grams, species, volume, full, kelvin)
    if (liquidShare <= 0L) return grams
    val critical = CRITICAL[species] ?: return grams
    // Density × volume, with the fullness applied last so a pipe's eighth of a tile does not round
    // its way to nothing before the density has been divided down.
    val mass = vapourR * critical.gramsPerTile / SCALE * (SCALE - liquidShare) / SCALE * volume / full
    return minOf(mass, grams)
}

fun liquidFraction(densityR: Long, temperatureR: Long): Long? {
    val vapour = saturatedVapourDensity(temperatureR) ?: return null
    val liquid = saturatedLiquidDensity(temperatureR) ?: return null
    if (densityR <= vapour) return 0L
    if (densityR >= liquid) return SCALE
    return (densityR - vapour) * SCALE / (liquid - vapour)
}
