package org.emerge.demo.outofspace.chem

import org.emerge.demo.outofspace.num.Budget
import org.emerge.demo.outofspace.num.isqrt
import org.emerge.demo.outofspace.num.scaledRatio

/**
 * The saturation curve: where a fluid holds liquid and vapour side by side, and at what pressure.
 *
 * [reducedPressure] on its own has a defect that is fatal to an explicit solver, and it is not a
 * rounding problem or a tuning problem — it is the equation being honest about something the grid
 * cannot represent. Over a wide band of densities the isotherm *falls* as the fluid is compressed,
 * so `dP/dρ` is negative and the speed of sound `√(dP/dρ)` is imaginary. A disturbance there does
 * not oscillate, it grows exponentially, and it grows *faster* the finer the grid. No timestep
 * stabilises it. Every cell straddling the surface of a pool sits in that band, because a cell
 * holding half a pool holds a density halfway between the two phases.
 *
 * The resolution is the one real fluids use: **the cell does not sit at that mean density, it
 * separates.** A tile holding "half a pool" is not a uniform fluid of intermediate density; it is
 * some liquid at [condensedDensity] and some vapour at [saturatedVapourDensity], and the
 * pressure it reports is neither branch's but the pressure the two coexist at — [saturationPressure],
 * the same value at every density across the band. So the falling stretch is replaced by a flat
 * one, `dP/dρ` becomes **zero rather than negative**, and the cell is neutrally stable instead of
 * explosively unstable.
 *
 * That flat line is not an approximation of the equation, it *is* what the equation predicts once a
 * cell is allowed to hold two phases at once. It is the Maxwell construction, fixed by a condition
 * with no freedom in it: the two phases must have equal fugacity, which is the same statement as
 * the equal-area rule, and `SaturationTest` re-derives these tables rather than trusting them.
 *
 * ### ⛔ There is a table per fluid now, and that is a property this file lost on purpose
 *
 * This used to say: "Because [reducedPressure] is in reduced units, the saturation curve is a
 * function of reduced temperature **and nothing else**. Water, nitrogen and carbon dioxide do not
 * get a table each; they read the same one at different places." That was true of van der Waals and
 * it is why van der Waals had to go — a law with no third constant cannot tell water from argon, and
 * `PhaseRealityTest` measures what that cost: **every fluid the vessel carries boiled between 13 K
 * and 118 K too cold**, and water's vapour pressure at room temperature read 129x the real one.
 * Argon has an acentric factor of exactly zero and was still 14 K out, so this was never only about
 * the missing constant: van der Waals puts critical compressibility at 3/8 where real fluids sit
 * near 0.27, and that displaces every species at once.
 *
 * Peng-Robinson's third constant is the **acentric factor**, a measured property of a substance in
 * exactly the way a critical temperature is. It enters through [Critical.kappa] and nothing else, so
 * two fluids with the same acentric factor still share a curve exactly — the dome is a one-parameter
 * family in κ rather than a single curve. **A phase transition still cannot be authored per
 * species**: what a species states is a number that was measured in a laboratory, and the shared law
 * does the rest. That is the property that mattered; universality of the *table* was its shape, not
 * its substance.
 *
 * ⚠️ **The cost is real and it scales with the fluids that gain a critical point.** Five today, so
 * five sets of three tables. If that count grows past a dozen, the escape hatch is to tabulate in
 * (Tr, κ) and interpolate the second axis — the family is smooth in κ — rather than to keep pasting
 * columns.
 */

/** Samples across `Tr = 0 .. 1`. Even spacing; index 0 is absolute zero, [N] − 1 the critical point. */
private const val N = 65

/**
 * The three branches of one fluid's saturation dome, all in [SCALE] and all sampled at the same [N]
 * reduced temperatures.
 *
 * Generated by solving the equal-fugacity condition to convergence at each sample — successive
 * substitution from Wilson's correlation, which is the standard method and, unlike an equal-area
 * quadrature in density, does not lose the vapour branch when it falls to `1e-8` of critical.
 * `SaturationTest` re-solves the condition and checks these values against it, so a corrupted entry
 * is caught rather than believed; `PhaseRealityTest` checks the result against measured boiling
 * points, which is the question re-solving the condition cannot ask.
 */
internal class Dome(
    /**
     * **Minus the natural logarithm** of the reduced saturation pressure at each sample, in
     * [NEG_LOG_SCALE]. [Long.MAX_VALUE] means the fugacity solve gave out — colder than any fluid
     * here has a liquid phase worth describing.
     *
     * ⛔ **Stored as a logarithm because a chord cannot fit an exponential.** Vapour pressure obeys
     * Clausius-Clapeyron, `ln P ≈ A − B/T`, which is a straight line in `1/T` and nothing like one
     * in `T`. Interpolating the pressure itself overshot by **7.7%** at the cold end; interpolating
     * its logarithm against `1/Tr` — the variable it is actually linear in — leaves **0.112%**.
     * The negation is so that every stored value is a positive integer.
     */
    val negLogSaturationPressure: LongArray,
    /**
     * Reduced density of the liquid that coexists at saturation — the dense branch, in [SCALE].
     *
     * ⚠️ **Linear, unlike the other two, and measured rather than assumed.** This branch is not
     * exponential: it runs from close packing down to critical density along a gentle curve, and
     * putting it in log space makes it *worse* — 0.033% against 0.063% over the cold range. What
     * error it has is the cusp at the top, which no change of basis fixes.
     *
     * Runs from near [CLOSE_PACKED] at absolute zero down to critical density at the critical point,
     * where it meets the vapour branch and the two phases stop being distinguishable.
     *
     * ⛔ The cold end holds the coldest value the solver reached, **not** [CLOSE_PACKED]. Clamping
     * it to the wall puts it above [MAX_REDUCED_DENSITY], so no density is ever "liquid", every cell
     * reads as [FluidPhase.Separating], and the tile reports zero pressure at every density.
     */
    val liquidDensity: LongArray,
    /**
     * Minus the natural logarithm of the reduced density of saturated vapour, in [NEG_LOG_SCALE] —
     * the sparse branch, and the density at which a gas can hold no more of itself.
     *
     * In log space for the same reason as the pressure, and it gains as much: **7.0% to 0.120%**
     * over the cold range. It tracks the saturation pressure closely enough that it is the same
     * curve wearing different units.
     *
     * Where this is small enough that [expNeg] rounds it to zero, any amount of the species at all
     * is at or above saturation, so a trace in a cold cell condenses completely rather than
     * lingering as a vapour. That is what makes a cold surface collect frost rather than ignore it.
     */
    val negLogVapourDensity: LongArray,
)

/** [DOMES] by ordinal, because this is read inside the pressure sweep. */
private val DOME_OF: Array<Dome?> = arrayOfNulls<Dome>(Species.COUNT).also {
    for ((species, dome) in DOMES) it[species.ordinal] = dome
}

/**
 * The coldest knot interval of each fluid's boiling curve that the fugacity solve actually reached,
 * or −1 for a fluid with no dome — see [Dome.negLogSaturationPressure], where the unreached samples
 * are [Long.MAX_VALUE].
 *
 * ⛔ **[vaporisationHeat] clamps to this rather than answering zero below it**, and the difference is
 * not a nicety. Zero says *this frost costs nothing to sublime*, which is false — ice at 5 K is
 * bound, and bound harder than ice at 200 K — and it says so as a **step**: one kelvin colder than
 * the first solved knot the latent heat fell off a cliff to nothing, which is a discontinuity of the
 * whole latent heat in a single degree. Clausius-Clapeyron says the opposite, that `B` barely moves
 * as a fluid gets colder, so continuing the coldest solved segment is both the honest extrapolation
 * and a continuous one.
 *
 * ⚠️ **Where the cliff sat varied by fluid**, which is why it went unnoticed: water reaches down to
 * 10 K and nothing in the game is that cold, but mercury's solve gives out below **273 K** and
 * zinc's below 49 K, so for the metal vapours the cliff was sitting in the middle of the ordinary
 * range. Computed here rather than in `SaturationTables.kt` because that file is generated and is
 * not to be edited by hand.
 */
private val COLDEST_SOLVED: IntArray = IntArray(Species.COUNT) { -1 }.also { out ->
    for (ordinal in 0 until Species.COUNT) {
        val table = DOME_OF[ordinal]?.negLogSaturationPressure ?: continue
        for (knot in 1 until N - 1) {
            if (table[knot] != Long.MAX_VALUE && table[knot + 1] != Long.MAX_VALUE) {
                out[ordinal] = knot
                break
            }
        }
    }
}

/**
 * Peng-Robinson's `α(Tr)` for [species], in [SCALE] — the temperature dependence of the attraction
 * term, and the only place the acentric factor enters the equation of state.
 *
 * `α = [1 + κ(1 − √Tr)]²`, with κ a per-species constant derived once from the acentric factor.
 *
 * ⛔ **Clamped at zero where the bracket would go negative.** Past `√Tr = 1 + 1/κ` the bracket
 * changes sign and squaring sends α *back up*, which is the well-known defect of this α function at
 * high temperature: attraction is supposed to vanish as a fluid gets hot, not return. For water that
 * turn is at about 2,980 K — reachable in a thruster bell and nowhere else — and letting it happen
 * would make a very hot gas start behaving as though it were sticky.
 *
 * ⚠️ **One integer square root per call**, which is why this is a function and not a table. A table
 * would have to span every reduced temperature the game reaches, and most of the vessel's gas is
 * *supercritical* — nitrogen at room temperature is at `Tr = 2.3` — so the interesting range is not
 * the `0..1` the dome tables cover. About 1,800 calls a tick on a 34×43 grid, which is well under a
 * percent of a core. If that ever matters, √Tr factors as `√T / √Tc` and √Tc is a per-species
 * constant that could be computed once.
 */
internal fun alphaAt(temperatureR: Long, species: Species): Long {
    val kappa = criticalOf(species)?.kappa ?: return SCALE
    if (temperatureR <= 0L) {
        val cold = SCALE + kappa
        return cold * cold / SCALE
    }
    val rootTr = isqrt(temperatureR * SCALE)
    val bracket = SCALE + kappa * (SCALE - rootTr) / SCALE
    if (bracket <= 0L) return 0L
    return bracket * bracket / SCALE
}

/** Natural logarithms are carried to six decimal places. See [Dome.negLogSaturationPressure]. */
private const val NEG_LOG_SCALE = 1_000_000L

/** `ln 2` in [NEG_LOG_SCALE], for the halving-and-remainder split in [expNeg]. */
private const val LN2 = 693_147L

/**
 * `2^(−j/64)` in [SCALE], for `j` in `0..64`.
 *
 * Shared by every fluid because this is arithmetic and not chemistry. Linear interpolation across a
 * sixty-fourth of an octave is good to about 15 parts per million, two orders below the 0.112% the
 * dome itself carries, so it contributes nothing to the error budget.
 */
private val POW2_NEG = longArrayOf(
        100000000L, 98922801L, 97857206L, 96803090L,
        95760328L, 94728799L, 93708382L, 92698956L,
        91700404L, 90712609L, 89735454L, 88768825L,
        87812608L, 86866692L, 85930965L, 85005318L,
        84089642L, 83183829L, 82287774L, 81401371L,
        80524517L, 79657108L, 78799042L, 77950220L,
        77110541L, 76279908L, 75458221L, 74645386L,
        73841307L, 73045890L, 72259040L, 71480667L,
        70710678L, 69948984L, 69195494L, 68450121L,
        67712777L, 66983376L, 66261832L, 65548061L,
        64841978L, 64143501L, 63452548L, 62769038L,
        62092891L, 61424027L, 60762368L, 60107837L,
        59460356L, 58819850L, 58186243L, 57559461L,
        56939432L, 56326081L, 55719337L, 55119129L,
        54525387L, 53938040L, 53357020L, 52782259L,
        52213689L, 51651244L, 51094857L, 50544464L,
        50000000L,
)

/**
 * `exp(−x / NEG_LOG_SCALE)`, in [SCALE] — the way back out of log space.
 *
 * Split into whole halvings and a remainder: `exp(−x) = 2^-n · 2^-f`, where the first is a shift and
 * the second is one lookup in [POW2_NEG]. No division by a variable, no floating point, and the
 * result is exact at the knots.
 *
 * ⚠️ **Guarded above forty halvings** rather than left to `shr`, which in Kotlin takes its count
 * modulo 64 and would turn a very small pressure into a very large one. Forty halvings is `1e-12`
 * of critical, far below anything [SCALE] can represent, so the guard costs nothing real.
 */
private fun expNeg(x: Long): Long {
    if (x <= 0L) return SCALE
    val halvings = x / LN2
    if (halvings > 40L) return 0L
    val remainder = x - halvings * LN2
    // `t · 64` in [SCALE], where `t` is how far through the octave the remainder sits.
    val position = remainder * 64L * SCALE / LN2
    val index = (position / SCALE).toInt()
    val fraction = position % SCALE
    val low = POW2_NEG[index]
    val base = low + (POW2_NEG[index + 1] - low) * fraction / SCALE
    return base shr halvings.toInt()
}

/**
 * Where [temperatureR] sits between knots [index] and `index + 1`, in [SCALE] — **measured in
 * `1/Tr`, not in `Tr`**.
 *
 * That is the whole of what makes the logarithmic tables worth having. `ln P` is a straight line in
 * reciprocal temperature and a curve in temperature, so interpolating the log against `Tr` recovers
 * most of the accuracy and interpolating it against `1/Tr` recovers nearly all of it: 0.921% against
 * 0.112% over the cold range, for one division.
 *
 * Rearranged so it never forms `1/Tr` explicitly — that would be a reciprocal of a reciprocal and
 * would throw away most of the precision it was supposed to buy. The algebra reduces to
 * `(i+1)·(64·Tr − i) / (64·Tr)`, and [scaledRatio] takes the fraction before the scale so the
 * numerator cannot run away.
 */
private fun logFraction(index: Int, temperatureR: Long): Long {
    val span = 64L * temperatureR
    return scaledRatio((index + 1L) * (span - index * SCALE), span, SCALE)
}

/**
 * Interpolation into one of the logarithmic branches, returning a value in [SCALE].
 *
 * Returns zero where either knot is out of the solver's reach, which is the honest rendering of a
 * vapour pressure too small for the equation to have solved for at all.
 *
 * ### What it costs, measured
 *
 * - **Saturation pressure: 0.028%**, against 6% when this branch was interpolated linearly. The
 *   figure the test reports is 0.12%, and that is [SCALE] quantisation rather than this function —
 *   at the cold end of the sweep the pressure is around 800 units and one unit of rounding is an
 *   eighth of a percent.
 * - **Vapour density: 0.12%** over the cold range, against 7.0% linear. Its worst case is 7.2% and
 *   sits in the last knot interval before the critical point, where the dome closes as `√(1 − Tr)`
 *   and no evenly-sampled table can follow a cusp. A change of basis does not help that and was
 *   never going to: it is a different defect, and it is the one [sample] documents.
 */
private fun sampleLog(table: LongArray, temperatureR: Long): Long {
    val position = temperatureR * (N - 1)
    val index = (position / SCALE).toInt()
    if (index >= N - 1) return expNeg(table[N - 1])
    // The first interval reaches down to absolute zero, where `1/Tr` has no value and the table has
    // nothing to interpolate from anyway.
    if (index <= 0) return 0L
    val low = table[index]
    val high = table[index + 1]
    if (low == Long.MAX_VALUE || high == Long.MAX_VALUE) return 0L
    return expNeg(low + (high - low) * logFraction(index, temperatureR) / SCALE)
}

/**
 * Linear interpolation into the dome's one non-logarithmic branch at reduced temperature
 * [temperatureR].
 *
 * Linear is enough, but the error is not uniform and it is worth knowing where it lives — all of it
 * is measured by `SaturationTest`, which re-solves the curve rather than trusting these numbers.
 *
 * ⚠️ **Only the liquid branch comes through here.** The other two are exponential and are stored as
 * logarithms — see [sampleLog], which is where their accuracy is discussed. What is left for this
 * one is the branch that is genuinely close to a straight line.
 *
 * - **The liquid density: within 5.1%**, and essentially all of it in the one knot interval below
 *   the critical point — 0.033% everywhere colder than `Tr = 0.9`. The dome closes
 *   as `√(1 − Tr)`, so both branches reach the critical point with infinite slope, and no table
 *   sampled evenly in `Tr` can follow a cusp. Sampling evenly in `√(1 − Tr)` instead would remove
 *   it, at the cost of a square root on this path; not done, because nothing in the vessel runs
 *   near a critical point.
 * Refining [N] moves it with a known exchange rate — the error is second order, so it falls
 * fourfold per doubling — if a use ever needs it to. Changing the *basis* would not: this branch is
 * already in the one it belongs in, which is exactly why the other two are not.
 */
private fun sample(table: LongArray, temperatureR: Long): Long {
    val position = temperatureR * (N - 1)
    val index = (position / SCALE).toInt()
    if (index >= N - 1) return table[N - 1]
    val fraction = position % SCALE
    val low = table[index]
    return low + (table[index + 1] - low) * fraction / SCALE
}

/**
 * The pressure at which liquid and vapour of [species] at reduced temperature [temperatureR] sit in
 * equilibrium — its **vapour pressure**, in [SCALE].
 *
 * This is the boiling curve, and it is the answer to the question the equation of state deliberately
 * refuses to answer directly: a fluid boils where this exceeds the pressure pressing on it. A pot of
 * water on a mountain and the same pot at sea level read the same curve here and boil at different
 * temperatures, because what changed was the other side of the comparison.
 *
 * Null above the critical temperature, where liquid and vapour are not different things and there is
 * nothing to be in equilibrium *between* — and null for a fluid with no dome at all.
 */
fun saturationPressure(temperatureR: Long, species: Species): Long? {
    val dome = DOME_OF[species.ordinal] ?: return null
    return if (temperatureR >= SCALE) null else sampleLog(dome.negLogSaturationPressure, temperatureR)
}

/**
 * Reduced density of the **condensed** phase at [temperatureR] — liquid above the triple point and
 * solid below it — or null above the critical point.
 *
 * ⚠️ **It was `condensedDensity` and the rename is not cosmetic.** Below
 * [Critical.triplePointKelvin] there is no liquid at any pressure, and answering with one is not a
 * labelling mistake: it hands [org.emerge.demo.outofspace.world.diffuseFluid] something that flows
 * where the world has something that does not.
 *
 * The solid branch is a **measured density** ([Species.solidKgPerCubicMetre]) rather than anything
 * the equation of state produces, because a cubic equation has no solid phase to produce it from —
 * see [Critical.solidDensityR]. So the branch steps at the triple point, which is real: matter does
 * change density when it freezes.
 *
 * ⛔ **For water the step goes the wrong way**, and it is worth knowing before it reads as a bug.
 * Ice really is *less* dense than liquid water — that anomaly is most of why water is interesting —
 * and here it comes out denser, because Peng-Robinson puts liquid water at the triple point around
 * 890 kg/m³ against a real 1000 while the ice branch is the measured 917. It is the equation's
 * liquid-density deficit showing through, not a claim about ice.
 */
fun condensedDensity(temperatureR: Long, species: Species): Long? {
    val c = criticalOf(species) ?: return null
    if (temperatureR >= SCALE) return null
    if (temperatureR < c.triplePointR) return c.solidDensityR
    val dome = DOME_OF[species.ordinal] ?: return null
    return sample(dome.liquidDensity, temperatureR)
}

/** Reduced density of saturated vapour at [temperatureR], or null above the critical point. */
fun saturatedVapourDensity(temperatureR: Long, species: Species): Long? {
    val dome = DOME_OF[species.ordinal] ?: return null
    return if (temperatureR >= SCALE) null else sampleLog(dome.negLogVapourDensity, temperatureR)
}

/**
 * The dome, sampled once per whole kelvin, per species — the form the simulation actually reads it in.
 *
 * ### Why a table on top of a table
 *
 * [DOMES] is 65 knots against *reduced* temperature, and reading it is not a lookup: [sampleLog]
 * interpolates in log space against `1/Tr`, which costs a [logFraction] — one `scaledRatio`, with a
 * variable denominator — and an [expNeg] on top. That is the right shape for a curve that has to
 * answer at any real temperature. It is the wrong shape for how it is asked.
 *
 * ⚠️ **Every call the simulation makes arrives with a whole kelvin.**
 * [org.emerge.demo.outofspace.world.settleCohesion] bisects on an `Int`,
 * [org.emerge.demo.outofspace.world.diffuseFluid] is handed an `IntArray`, and
 * [org.emerge.demo.outofspace.world.tilePressure] reads one per tile. There is nothing in between
 * two kelvin for the interpolation to find, so it was re-deriving, millions of times a second, one
 * of a few thousand distinct answers.
 *
 * ⚠️ Measured: `sampleLog` and the [logFraction] under it were **26% of every execution sample in
 * the game**, spread across the fluid, pressure and diffusion phases.
 *
 * ### What it costs to hold
 *
 * One entry per kelvin from absolute zero up to the species' own critical temperature, because above
 * that all three curves are null and there is nothing to hold. The hottest critical point in the
 * table is zinc at 3,170 K, most are far colder, and only the fluids have domes at all — three
 * `LongArray`s totalling well under a megabyte for the whole vessel's chemistry, built once.
 *
 * ⛔ **Memoisation, not approximation.** Each entry is what the curve itself returns at that kelvin,
 * so every reading is bit-for-bit what interpolating would have produced. `DomeTableTest` asserts
 * that against the curve at every kelvin of every species, which is the only thing that keeps this
 * from becoming a second, quietly diverging source of truth.
 */
private class DomeTable(
    val vapourDensity: LongArray,
    val condensedDensity: LongArray,
    val saturationPressure: LongArray,
)

private val DOME_AT: Array<DomeTable?> = Array(Species.COUNT) { ordinal ->
    val species = Species.ALL[ordinal]
    val critical = criticalOf(species)
    // Both, and not just one: `condensedDensity` answers off `solidDensityR` below the triple point
    // without consulting the dome at all, so a species with a critical point and no dome would tabulate
    // two curves and be missing the third. Nothing in the game is in that position today, and the
    // accessors fall back to the curve rather than assuming it stays that way.
    if (critical == null || DOME_OF[ordinal] == null) null
    else DomeTable(
        LongArray(critical.kelvin) { k -> saturatedVapourDensity(reducedTemperature(k, species)!!, species)!! },
        LongArray(critical.kelvin) { k -> condensedDensity(reducedTemperature(k, species)!!, species)!! },
        LongArray(critical.kelvin) { k -> saturationPressure(reducedTemperature(k, species)!!, species)!! },
    )
}

/**
 * Whether [kelvin] is inside [species]' table — i.e. non-negative and below its critical point.
 *
 * ⚠️ The bound is exactly the curve's own `temperatureR >= SCALE` test, not an approximation of it:
 * `kelvin × SCALE / c.kelvin >= SCALE` holds precisely when `kelvin >= c.kelvin`, so the table ends
 * where the answers start being null and the two agree at the seam by construction.
 */
private fun tabled(kelvin: Int, table: DomeTable?): Boolean =
    table != null && kelvin >= 0 && kelvin < table.vapourDensity.size

/** [saturatedVapourDensity] at a whole [kelvin] — see [DomeTable]. */
fun saturatedVapourDensityAt(kelvin: Int, species: Species): Long? {
    val table = DOME_AT[species.ordinal]
    if (!tabled(kelvin, table)) return saturatedVapourDensity(reducedTemperature(kelvin, species) ?: return null, species)
    return table!!.vapourDensity[kelvin]
}

/** [condensedDensity] at a whole [kelvin] — see [DomeTable]. */
fun condensedDensityAt(kelvin: Int, species: Species): Long? {
    val table = DOME_AT[species.ordinal]
    if (!tabled(kelvin, table)) return condensedDensity(reducedTemperature(kelvin, species) ?: return null, species)
    return table!!.condensedDensity[kelvin]
}

/** [saturationPressure] at a whole [kelvin] — see [DomeTable]. */
fun saturationPressureAt(kelvin: Int, species: Species): Long? {
    val table = DOME_AT[species.ordinal]
    if (!tabled(kelvin, table)) return saturationPressure(reducedTemperature(kelvin, species) ?: return null, species)
    return table!!.saturationPressure[kelvin]
}

/**
 * What fraction of a cell's volume is liquid, in [SCALE], for a cell inside the saturation dome —
 * the **lever rule**.
 *
 * A cell at mean density `ρ` between the two branches holds liquid at `ρl` and vapour at `ρv` in
 * whatever proportion averages to `ρ`, which fixes the split with no freedom left over:
 * `f = (ρ − ρv) / (ρl − ρv)`. Zero at the vapour branch, one at the liquid branch, and sweeping from
 * one to the other *is* boiling — a cell does not jump between phases, it crosses the dome, and how
 * far across it has got is this number.
 *
 * Returns 0 below the dome, [SCALE] above it, and null above the critical temperature.
 */
fun condensedFraction(densityR: Long, temperatureR: Long, species: Species): Long? {
    val vapour = saturatedVapourDensity(temperatureR, species) ?: return null
    val liquid = condensedDensity(temperatureR, species) ?: return null
    return leverRule(densityR, vapour, liquid)
}

/** [condensedFraction] at a whole [kelvin], off the table rather than the curve — see [DomeTable]. */
fun condensedFractionAt(densityR: Long, kelvin: Int, species: Species): Long? {
    val vapour = saturatedVapourDensityAt(kelvin, species) ?: return null
    val liquid = condensedDensityAt(kelvin, species) ?: return null
    return leverRule(densityR, vapour, liquid)
}

/**
 * The lever rule itself, given the two branches — the arithmetic both readings above share.
 *
 * Split out so the *rule* is stated once and the two functions differ only in how they reach the
 * dome. Two copies of `(ρ − ρv)/(ρl − ρv)` would be two places to get an inclusive bound wrong, and
 * the bounds are load-bearing: [phaseAt] reads a cell at exactly the saturated liquid density as
 * wholly liquid because this does.
 */
private fun leverRule(densityR: Long, vapour: Long, liquid: Long): Long = when {
    densityR <= vapour -> 0L
    densityR >= liquid -> SCALE
    else -> (densityR - vapour) * SCALE / (liquid - vapour)
}

/**
 * How much of a cell [species] fills as *liquid*, in [SCALE] — the share of the room that is taken
 * and is no longer available to anything else.
 *
 * **A liquid displaces the gas above it, and until this existed nothing here said so.** Every
 * species shared the whole cell, so a pool of water contributed its vapour pressure *on top of* an
 * undisturbed atmosphere of nitrogen, which put the tile holding it at 1.66 atm against neighbours
 * at 1.00 and blew it apart within a handful of ticks — mass conserved, no instability, the pool
 * simply pushed itself across the room. That looked like the stiffness problem returning and is
 * something else entirely: a pool cannot sit still until the nitrogen has somewhere to not be.
 *
 * Returns 0 for a species that is not condensing.
 */
fun condensedVolumeFraction(mass: Long, species: Species, volume: Int, full: Int, kelvin: Int): Long {
    val densityR = reducedDensity(mass, species, volume, full) ?: return 0L
    return condensedFractionAt(densityR, kelvin, species) ?: 0L
}

/**
 * How many of a cell's [mass] of [species] are present as **vapour** — the rest being liquid.
 *
 * The lever rule again, read as a mass rather than as a volume: the cell holds `1 − f` of its room
 * at [saturatedVapourDensity], and that volume times that density is this. Returns all of [mass] for
 * a species that is not condensing.
 *
 * This exists because **the two phases are not the same substance as far as transport is
 * concerned.** Fick's law describes a mixture spreading through itself, and a pool sitting under an
 * atmosphere is not a mixture — it is two phases with an interface. Differencing concentration
 * across that interface makes the pool read as an infinitely steep gradient and drift dissolves it,
 * which is measurably what was happening: a saturated pool shed 76% of itself in twenty ticks, and
 * excluding its liquid from drift leaves it holding 87%.
 *
 * ⚠️ **Nothing calls this yet**, and the clamp on the last line is why that is worth saying: it read
 * `minOf(mass, mass)` against a `val mass` that shadowed the parameter, so the vapour it reported
 * was never limited by the mass actually present and could exceed it. Harmless while dead;
 * corrected here rather than left for whoever wires up the phase-aware transport it was written for.
 */
fun vapourMass(mass: Long, species: Species, volume: Int, full: Int, kelvin: Int): Long {
    if (mass <= 0L) return mass
    val vapourR = saturatedVapourDensityAt(kelvin, species) ?: return mass
    val condensedShare = condensedVolumeFraction(mass, species, volume, full, kelvin)
    if (condensedShare <= 0L) return mass
    // Density × volume, with the fullness applied last so a pipe's eighth of a tile does not round
    // its way to nothing before the density has been divided down — hence the full tile asked for
    // here and the `volume / full` at the end rather than letting the helper do it.
    val fullTile = massAtReducedDensity(vapourR, species, full, full) ?: return mass
    val asVapour = scaledRatio(SCALE - condensedShare, SCALE, fullTile) * volume / full
    return minOf(asVapour, mass)
}

/** `R × 10⁴`, so the gas constant can be carried without floating point. */
private const val GAS_CONSTANT_SCALED = 83_145L

/**
 * The energy it takes to turn [mass] of [species] at [kelvin] from its condensed phase into vapour,
 * in the simulation's energy units — the **latent heat**, and positive because it has to be paid.
 *
 * ⛔ **Nothing states a latent heat anywhere, and nothing should.** It is not an independent property
 * of a substance; it is the slope of that substance's own boiling curve, and this file already has
 * the curve. Clausius and Clapeyron:
 *
 *     ΔH = R · T² · d(ln P_sat)/dT
 *
 * which in reduced units is `ΔH/(R·Tc) = Tr² · d(ln Pr)/dTr` — and `ln Pr` is exactly what
 * [Dome.negLogSaturationPressure] holds, so the derivative is one subtraction between knots. A
 * species that boils at a high temperature has a steep curve and a large latent heat *because* those
 * are the same fact, and inventing a table of enthalpies alongside the pressures would be a second
 * source of truth for a number the first one already answers.
 *
 * ⚠️ **Below the triple point this is the heat of SUBLIMATION and it comes out larger, for free.**
 * The table carries the sublimation branch down there and that branch is steeper by exactly the heat
 * of fusion — which is what makes it steeper. Frost costs more to lift than a puddle does, and
 * nothing here had to be told so.
 *
 * ⚠️ **About 7% high**, measured against water at its boiling point: 43.6 kJ/mol against a real
 * 40.65. The exact relation carries a compressibility factor `Δz` for the volume the vapour occupies
 * against the liquid, and this uses the ideal form that drops it. Worth knowing before trusting the
 * figure quantitatively; the shape — that it grows as a fluid gets colder and vanishes at the
 * critical point — is right, and it is the shape that does the work.
 *
 * Zero for a species with no critical point on file, which is the correct answer rather than a
 * fallback: something that has no liquid phase in this model is already a gas and costs nothing to
 * make into one.
 */
fun vaporisationHeat(mass: Long, species: Species, kelvin: Int): Long {
    if (mass <= 0L) return 0L
    val critical = criticalOf(species) ?: return 0L
    val dome = DOME_OF[species.ordinal] ?: return 0L
    val temperatureR = reducedTemperature(kelvin, species) ?: return 0L
    // At and above the critical point there is no phase change to pay for: the distinction between
    // liquid and vapour has stopped existing, which is the same reason the dome closes there.
    if (temperatureR >= SCALE) return 0L

    // Colder than the solve reached, the coldest segment it did reach is continued — see
    // [COLDEST_SOLVED]. Above the top knot there is nothing to continue: the dome has closed.
    val coldest = COLDEST_SOLVED[species.ordinal]
    if (coldest < 0) return 0L
    val position = temperatureR * (N - 1)
    val at = (position / SCALE).toInt()
    if (at >= N - 1) return 0L
    val index = if (at < coldest) coldest else at
    val low = dome.negLogSaturationPressure[index]
    val high = dome.negLogSaturationPressure[index + 1]

    // The chord across this knot interval, in [NEG_LOG_SCALE]. The table is *minus* the logarithm
    // and falls as the temperature rises, so the subtraction is this way round and the result is
    // positive.
    val slope = (low - high) * (N - 1)
    if (slope <= 0L) return 0L

    // ⛔ **`Tr_i · Tr_{i+1}`, and NOT `Tr²`.** This is the one line that has to agree with
    // [sampleLog], and for a long time it did not.
    //
    // The curve these knots describe is `ln Pr = A − B/Tr` — that is *why* [sampleLog] interpolates
    // against `1/Tr` rather than against `Tr`, and the 0.028% it reports is the measure of how well
    // the table obeys it. Differentiate the model the table is actually read as, and
    // `d(ln Pr)/dTr = B/Tr²`, so the `Tr²` in Clausius-Clapeyron **cancels exactly** and the latent
    // heat is `B` alone — which is the physical statement that a fluid obeying Clausius-Clapeyron
    // has a latent heat that does not depend on temperature.
    //
    // `B` follows from the two knots: `L_i − L_{i+1} = B(1/Tr_i − 1/Tr_{i+1})`, and since the
    // samples are evenly spaced the reciprocal difference is `(1/64) / (Tr_i · Tr_{i+1})`. So `B`
    // is the chord above times the two knot temperatures, and the temperature *inside* the interval
    // does not enter at all.
    //
    // ⚠️ **What it was doing instead**, and the failure is worth stating because it was invisible:
    // it took the chord as though the curve were straight in `Tr` and then multiplied by the live
    // `Tr²`. Those are two different models of the same table and the mismatch **double-counts the
    // temperature dependence**, so within every knot interval the latent heat *climbed* with
    // temperature — backwards, since it has to vanish at the critical point — and then fell off a
    // cliff at the next knot. For water at 200 K it rose 3% across three kelvin and then dropped 7%
    // in one: measured, a rise of 2.8 MJ/kg per kelvin against a specific heat of 4.18 kJ/kg/K,
    // **6.8 times steeper than the tile's own heat capacity**.
    //
    // ⛔ That is what broke [org.emerge.demo.outofspace.world.settleCohesion], whose bisection rests
    // on `capacity·T + cohesion(T)` being strictly increasing. It was solving a sawtooth: a tile
    // holding 20 kg of water frost, exactly consistent at 200 K, settled to **171 K** on the first
    // call and booked 245 MJ of energy across the bond boundary for having been asked a question.
    // `LatentHeatTest` now asserts the slope bound directly, per species and per kelvin, because a
    // solver's precondition that nothing checks is a solver's precondition that drifts.
    val trLow = index.toLong() * SCALE / (N - 1)
    val trHigh = (index + 1).toLong() * SCALE / (N - 1)
    val knots = trLow * trHigh / SCALE

    // `B` itself, in [NEG_LOG_SCALE]. On the sublimation branch this comes out **constant to seven
    // digits** across every knot interval — 9 490 19x for water, all the way from 10 K to the triple
    // point — which is the table saying plainly that it was generated by extending
    // Clausius-Clapeyron at a fixed heat of sublimation, exactly as `SaturationTables.kt` claims. It
    // then steps down at the triple point by the heat of fusion and falls away toward the critical
    // point, and both of those are the direction that keeps a settlement monotone.
    val b = slope * knots / SCALE
    if (b <= 0L) return 0L

    // ⚠️ **One divide, and it is at the end.** `rTc · knots / SCALE` as its own step truncated a
    // value of 2.6 to **2** in the coldest knot interval, because `knots` is `Tr_i · Tr_{i+1}` and
    // that is a small number down there. The constant `B` above then came back out of this function
    // as a curve that climbed 31% from 10 K to 100 K — an artifact of integer division masquerading
    // as physics, and the last thing standing between a settlement and a monotone function to solve.
    val joulesPerMole = GAS_CONSTANT_SCALED * critical.kelvin * b / (10_000L * NEG_LOG_SCALE)
    if (joulesPerMole <= 0L) return 0L

    // Per mole to per kilogram to the simulation's units, by the route every enthalpy in `chem`
    // takes — see [kJPerMolAt], whose divisor is a formula mass in grams.
    return perKilogram(mass, joulesPerMole * 1_000L * Budget.JOULE / species.molarMass)
}
