package org.emerge.demo.outofspace.chem

import org.emerge.demo.outofspace.num.isqrt
import org.emerge.demo.outofspace.num.scaledRatio

/**
 * The saturation curve: where a fluid holds liquid and vapour side by side, and at what pressure.
 *
 * [reducedPressure] on its own has a defect that is fatal to an explicit solver, and it is not a
 * rounding problem or a tuning problem — it is the equation being honest about something the grid
 * cannot represent. Over a wide band of densities the isotherm *falls* as the fluid is compressed,
 * so `dP/dρ` is negative and the speed of sound `√(dP/dρ)` is imaginary. A disturbance there does
 * not oscillate, it grows exponentially, and it grows *faster* the finer the grid. No timestep
 * stabilises it. Every cell straddling the surface of a pool sits in that band, because a cell
 * holding half a pool holds a density halfway between the two phases.
 *
 * The resolution is the one real fluids use: **the cell does not sit at that mean density, it
 * separates.** A tile holding "half a pool" is not a uniform fluid of intermediate density; it is
 * some liquid at [condensedDensity] and some vapour at [saturatedVapourDensity], and the
 * pressure it reports is neither branch's but the pressure the two coexist at — [saturationPressure],
 * the same value at every density across the band. So the falling stretch is replaced by a flat
 * one, `dP/dρ` becomes **zero rather than negative**, and the cell is neutrally stable instead of
 * explosively unstable.
 *
 * That flat line is not an approximation of the equation, it *is* what the equation predicts once a
 * cell is allowed to hold two phases at once. It is the Maxwell construction, fixed by a condition
 * with no freedom in it: the two phases must have equal fugacity, which is the same statement as
 * the equal-area rule, and `SaturationTest` re-derives these tables rather than trusting them.
 *
 * ### ⛔ There is a table per fluid now, and that is a property this file lost on purpose
 *
 * This used to say: "Because [reducedPressure] is in reduced units, the saturation curve is a
 * function of reduced temperature **and nothing else**. Water, nitrogen and carbon dioxide do not
 * get a table each; they read the same one at different places." That was true of van der Waals and
 * it is why van der Waals had to go — a law with no third constant cannot tell water from argon, and
 * `PhaseRealityTest` measures what that cost: **every fluid the vessel carries boiled between 13 K
 * and 118 K too cold**, and water's vapour pressure at room temperature read 129x the real one.
 * Argon has an acentric factor of exactly zero and was still 14 K out, so this was never only about
 * the missing constant: van der Waals puts critical compressibility at 3/8 where real fluids sit
 * near 0.27, and that displaces every species at once.
 *
 * Peng-Robinson's third constant is the **acentric factor**, a measured property of a substance in
 * exactly the way a critical temperature is. It enters through [Critical.kappa] and nothing else, so
 * two fluids with the same acentric factor still share a curve exactly — the dome is a one-parameter
 * family in κ rather than a single curve. **A phase transition still cannot be authored per
 * species**: what a species states is a number that was measured in a laboratory, and the shared law
 * does the rest. That is the property that mattered; universality of the *table* was its shape, not
 * its substance.
 *
 * ⚠️ **The cost is real and it scales with the fluids that gain a critical point.** Five today, so
 * five sets of three tables. If that count grows past a dozen, the escape hatch is to tabulate in
 * (Tr, κ) and interpolate the second axis — the family is smooth in κ — rather than to keep pasting
 * columns.
 */

/** Samples across `Tr = 0 .. 1`. Even spacing; index 0 is absolute zero, [N] − 1 the critical point. */
private const val N = 65

/**
 * The three branches of one fluid's saturation dome, all in [SCALE] and all sampled at the same [N]
 * reduced temperatures.
 *
 * Generated by solving the equal-fugacity condition to convergence at each sample — successive
 * substitution from Wilson's correlation, which is the standard method and, unlike an equal-area
 * quadrature in density, does not lose the vapour branch when it falls to `1e-8` of critical.
 * `SaturationTest` re-solves the condition and checks these values against it, so a corrupted entry
 * is caught rather than believed; `PhaseRealityTest` checks the result against measured boiling
 * points, which is the question re-solving the condition cannot ask.
 */
private class Dome(
    /**
     * **Minus the natural logarithm** of the reduced saturation pressure at each sample, in
     * [NEG_LOG_SCALE]. [Long.MAX_VALUE] means the fugacity solve gave out — colder than any fluid
     * here has a liquid phase worth describing.
     *
     * ⛔ **Stored as a logarithm because a chord cannot fit an exponential.** Vapour pressure obeys
     * Clausius-Clapeyron, `ln P ≈ A − B/T`, which is a straight line in `1/T` and nothing like one
     * in `T`. Interpolating the pressure itself overshot by **7.7%** at the cold end; interpolating
     * its logarithm against `1/Tr` — the variable it is actually linear in — leaves **0.112%**.
     * The negation is so that every stored value is a positive integer.
     */
    val negLogSaturationPressure: LongArray,
    /**
     * Reduced density of the liquid that coexists at saturation — the dense branch, in [SCALE].
     *
     * ⚠️ **Linear, unlike the other two, and measured rather than assumed.** This branch is not
     * exponential: it runs from close packing down to critical density along a gentle curve, and
     * putting it in log space makes it *worse* — 0.033% against 0.063% over the cold range. What
     * error it has is the cusp at the top, which no change of basis fixes.
     *
     * Runs from near [CLOSE_PACKED] at absolute zero down to critical density at the critical point,
     * where it meets the vapour branch and the two phases stop being distinguishable.
     *
     * ⛔ The cold end holds the coldest value the solver reached, **not** [CLOSE_PACKED]. Clamping
     * it to the wall puts it above [MAX_REDUCED_DENSITY], so no density is ever "liquid", every cell
     * reads as [FluidPhase.Separating], and the tile reports zero pressure at every density.
     */
    val liquidDensity: LongArray,
    /**
     * Minus the natural logarithm of the reduced density of saturated vapour, in [NEG_LOG_SCALE] —
     * the sparse branch, and the density at which a gas can hold no more of itself.
     *
     * In log space for the same reason as the pressure, and it gains as much: **7.0% to 0.120%**
     * over the cold range. It tracks the saturation pressure closely enough that it is the same
     * curve wearing different units.
     *
     * Where this is small enough that [expNeg] rounds it to zero, any amount of the species at all
     * is at or above saturation, so a trace in a cold cell condenses completely rather than
     * lingering as a vapour. That is what makes a cold surface collect frost rather than ignore it.
     */
    val negLogVapourDensity: LongArray,
)

/**
 * Every fluid that has a saturation dome, which is every fluid with an entry in [CRITICAL].
 *
 * ⚠️ A fluid absent from here has no phase behaviour at all and is an ideal gas at every
 * temperature — see [CRITICAL], which is the single place that decides it.
 */
private val DOMES: Map<Species, Dome> = mapOf(
    Species.Water to Dome(
        negLogSaturationPressure = longArrayOf(
            Long.MAX_VALUE, 595616900L, 291930597L, 190701829L,
            140087445L, 109718815L, 89473061L, 75011809L,
            64165869L, 55730139L, 48981554L, 43459985L,
            38858677L, 34965263L, 31628051L, 28735800L,
            26205081L, 23972094L, 21987216L, 20211273L,
            18612924L, 17166798L, 15852139L, 14651798L,
            13551485L, 12539198L, 11604778L, 10739575L,
            10003827L, 9326858L, 8701508L, 8122509L,
            7585259L, 7085717L, 6620317L, 6185899L,
            5779654L, 5399072L, 5041907L, 4706144L,
            4389968L, 4091742L, 3809988L, 3543369L,
            3290674L, 3050804L, 2822760L, 2605636L,
            2398605L, 2200914L, 2011875L, 1830861L,
            1657297L, 1490657L, 1330457L, 1176254L,
            1027638L, 884233L, 745690L, 611688L,
            481926L, 356127L, 234032L, 115399L,
            0L,
        ),
        liquidDensity = longArrayOf(
            356489161L, 356489161L, 356489161L, 356489161L,
            356489161L, 356489161L, 356489161L, 356489161L,
            356489161L, 356489161L, 356489161L, 356489161L,
            356489161L, 356489161L, 356489161L, 356489161L,
            356489161L, 356489161L, 356489161L, 356489161L,
            356489161L, 356489161L, 356489161L, 356489161L,
            356489161L, 356489161L, 356489161L, 356489161L,
            356489161L, 354234143L, 351895895L, 349470551L,
            346953934L, 344341529L, 341628444L, 338809378L,
            335878577L, 332829783L, 329656184L, 326350345L,
            322904136L, 319308644L, 315554068L, 311629600L,
            307523270L, 303221772L, 298710241L, 293971983L,
            288988132L, 283737219L, 278194616L, 272331808L,
            266115417L, 259505874L, 252455551L, 244906062L,
            236784212L, 227995640L, 218414283L, 207863633L,
            196080167L, 182632039L, 166698487L, 146210657L,
            100000000L,
        ),
        negLogVapourDensity = longArrayOf(
            Long.MAX_VALUE, 592637618L, 289644462L, 188821159L,
            138494457L, 108348971L, 88285539L, 73978437L,
            63266029L, 54948081L, 48304857L, 42878598L,
            38364302L, 34550931L, 31287826L, 28464569L,
            25998388L, 23826025L, 21898306L, 20176430L,
            18629374L, 17232039L, 15963899L, 14808008L,
            13750250L, 12778773L, 11883551L, 11056039L,
            10356577L, 9714560L, 9122887L, 8576335L,
            8070325L, 7600827L, 7164274L, 6757489L,
            6377637L, 6022174L, 5688810L, 5375479L,
            5080314L, 4801618L, 4537850L, 4287606L,
            4049600L, 3822656L, 3605689L, 3397693L,
            3197733L, 3004929L, 2818446L, 2637478L,
            2461240L, 2288942L, 2119776L, 1952882L,
            1787310L, 1621956L, 1455467L, 1286056L,
            1111160L, 926657L, 724746L, 485566L,
            0L,
        ),
    ),
    Species.Nitrogen to Dome(
        negLogSaturationPressure = longArrayOf(
            Long.MAX_VALUE, 411536511L, 202005846L, 132162291L,
            97240514L, 76287447L, 62318736L, 52341085L,
            44857847L, 39037551L, 34381314L, 30571666L,
            27396959L, 24710668L, 22408133L, 20412603L,
            18666514L, 17125848L, 15756366L, 14531041L,
            13428248L, 12430483L, 11523424L, 10695239L,
            9936070L, 9237634L, 8592925L, 7995971L,
            7441657L, 6925572L, 6443892L, 5993289L,
            5570848L, 5224784L, 4902110L, 4599320L,
            4314611L, 4046382L, 3793202L, 3553792L,
            3327006L, 3111814L, 2907290L, 2712599L,
            2526986L, 2349767L, 2180324L, 2018094L,
            1862565L, 1713270L, 1569783L, 1431714L,
            1298707L, 1170432L, 1046589L, 926900L,
            811109L, 698979L, 590290L, 484841L,
            382441L, 282915L, 186100L, 91843L,
            0L,
        ),
        liquidDensity = longArrayOf(
            330076514L, 330076514L, 330076514L, 330076514L,
            330076514L, 330076514L, 330076514L, 330076514L,
            330076514L, 330076514L, 330076514L, 330076514L,
            330076514L, 330076514L, 330076514L, 330076514L,
            330076514L, 330076514L, 330076514L, 330076514L,
            330076514L, 330076514L, 330076514L, 330076514L,
            330076514L, 330076514L, 330076514L, 330076514L,
            330076514L, 330076514L, 330076514L, 330076514L,
            330076514L, 330076514L, 327004580L, 323837527L,
            320570710L, 317199108L, 313717287L, 310119349L,
            306398877L, 302548867L, 298561646L, 294428779L,
            290140950L, 285687818L, 281057850L, 276238095L,
            271213916L, 265968636L, 260483092L, 254735031L,
            248698311L, 242341799L, 235627808L, 228509833L,
            220929128L, 212809307L, 204047348L, 194497534L,
            183939965L, 172010338L, 158008811L, 140153394L,
            100000000L,
        ),
        negLogVapourDensity = longArrayOf(
            Long.MAX_VALUE, 408557229L, 199719711L, 130281622L,
            95647526L, 74917603L, 61131214L, 51307714L,
            43958007L, 38255494L, 33704617L, 29990279L,
            26902583L, 24296336L, 22067909L, 20141372L,
            18459821L, 16979779L, 15667455L, 14496194L,
            13444689L, 12495700L, 11635133L, 10851346L,
            10134638L, 9476854L, 8871087L, 8311440L,
            7792840L, 7310896L, 6861778L, 6442125L,
            6048966L, 5731017L, 5434991L, 5157363L,
            4896324L, 4650260L, 4417728L, 4197432L,
            3988209L, 3789006L, 3598873L, 3416941L,
            3242421L, 3074584L, 2912759L, 2756317L,
            2604669L, 2457254L, 2313528L, 2172961L,
            2035018L, 1899151L, 1764783L, 1631276L,
            1497909L, 1363813L, 1227894L, 1088672L,
            943983L, 790295L, 620850L, 418345L,
            0L,
        ),
    ),
    Species.Oxygen to Dome(
        negLogSaturationPressure = longArrayOf(
            Long.MAX_VALUE, 399080780L, 195665043L, 127859797L,
            93957175L, 73615601L, 60054552L, 50368088L,
            43103240L, 37452803L, 32932454L, 29233986L,
            26151929L, 23544035L, 21308697L, 19371404L,
            17676273L, 16180569L, 14851055L, 13661489L,
            12590880L, 11622234L, 10741646L, 9965931L,
            9285880L, 8664161L, 8093839L, 7569011L,
            7084616L, 6636293L, 6220260L, 5833223L,
            5472298L, 5134954L, 4818957L, 4522331L,
            4243322L, 3980371L, 3732087L, 3497224L,
            3274669L, 3063420L, 2862576L, 2671324L,
            2488932L, 2314734L, 2148128L, 1988567L,
            1835554L, 1688634L, 1547392L, 1411450L,
            1280460L, 1154102L, 1032083L, 914133L,
            800002L, 689460L, 582293L, 478303L,
            377307L, 279133L, 183621L, 90624L,
            0L,
        ),
        liquidDensity = longArrayOf(
            355695822L, 355695822L, 355695822L, 355695822L,
            355695822L, 355695822L, 355695822L, 355695822L,
            355695822L, 355695822L, 355695822L, 355695822L,
            355695822L, 355695822L, 355695822L, 355695822L,
            355695822L, 355695822L, 355695822L, 355695822L,
            355695822L, 355695822L, 355695822L, 355695822L,
            353356294L, 350953887L, 348486376L, 345951370L,
            343346299L, 340668404L, 337914722L, 335082073L,
            332167040L, 329165955L, 326074872L, 322889544L,
            319605391L, 316217468L, 312720423L, 309108447L,
            305375224L, 301513857L, 297516795L, 293375734L,
            289081505L, 284623930L, 279991655L, 275171928L,
            270150338L, 264910459L, 259433412L, 253697268L,
            247676258L, 241339679L, 234650349L, 227562367L,
            220017720L, 211940933L, 203230161L, 193741264L,
            183256604L, 171415424L, 157524325L, 139816882L,
            100000000L,
        ),
        negLogVapourDensity = longArrayOf(
            Long.MAX_VALUE, 396101498L, 193378908L, 125979128L,
            92364187L, 72245757L, 58867029L, 49334716L,
            42203400L, 36670746L, 32255757L, 28652599L,
            25657554L, 23129702L, 20968473L, 19100173L,
            17469580L, 16034500L, 14762142L, 13626638L,
            12607309L, 11687424L, 10853297L, 10121928L,
            9484266L, 8903100L, 8371595L, 7883924L,
            7435086L, 7020761L, 6637198L, 6281122L,
            5949662L, 5640289L, 5350770L, 5079126L,
            4823597L, 4582614L, 4354776L, 4138823L,
            3933624L, 3738159L, 3551502L, 3372812L,
            3201319L, 3036317L, 2877152L, 2723212L,
            2573924L, 2428740L, 2287131L, 2148577L,
            2012555L, 1878530L, 1745931L, 1614135L,
            1482429L, 1349957L, 1215636L, 1078004L,
            934915L, 782871L, 615170L, 414650L,
            0L,
        ),
    ),
    Species.CarbonDioxide to Dome(
        negLogSaturationPressure = longArrayOf(
            Long.MAX_VALUE, 648757296L, 318466068L, 208368992L,
            153320454L, 120291332L, 98271916L, 82543763L,
            70747647L, 61572891L, 54233086L, 48227791L,
            43223378L, 38988876L, 35359302L, 32213671L,
            29461244L, 27032632L, 24873866L, 22942338L,
            21203963L, 19631148L, 18201316L, 16895817L,
            15699109L, 14598139L, 13581858L, 12640857L,
            11767071L, 10953546L, 10194256L, 9483952L,
            8818042L, 8192491L, 7603736L, 7048625L,
            6524353L, 6028420L, 5558589L, 5112852L,
            4689402L, 4286608L, 3902994L, 3537223L,
            3188078L, 2854451L, 2582632L, 2386382L,
            2198886L, 2019505L, 1847657L, 1682808L,
            1524471L, 1372198L, 1225579L, 1084236L,
            947822L, 816016L, 688522L, 565064L,
            445389L, 329258L, 216452L, 106763L,
            0L,
        ),
        liquidDensity = longArrayOf(
            292824465L, 292824465L, 292824465L, 292824465L,
            292824465L, 292824465L, 292824465L, 292824465L,
            292824465L, 292824465L, 292824465L, 292824465L,
            292824465L, 292824465L, 292824465L, 292824465L,
            292824465L, 292824465L, 292824465L, 292824465L,
            292824465L, 292824465L, 292824465L, 292824465L,
            292824465L, 292824465L, 292824465L, 292824465L,
            292824465L, 292824465L, 292824465L, 292824465L,
            292824465L, 292824465L, 292824465L, 292824465L,
            292824465L, 292824465L, 292824465L, 292824465L,
            292824465L, 292824465L, 292824465L, 292824465L,
            292824465L, 292824465L, 292824465L, 288041329L,
            283025948L, 277758580L, 272216578L, 266373708L,
            260199239L, 253656702L, 246702133L, 239281537L,
            231327066L, 222751014L, 213435837L, 203216382L,
            191845131L, 178914853L, 163648453L, 144079587L,
            100000000L,
        ),
        negLogVapourDensity = longArrayOf(
            Long.MAX_VALUE, 645778014L, 316179934L, 206488323L,
            151727467L, 118921488L, 97084394L, 81510391L,
            69847807L, 60790834L, 53556389L, 47646404L,
            42729003L, 38574543L, 35019077L, 31942439L,
            29254551L, 26886563L, 24784956L, 22907495L,
            21220414L, 19696388L, 18313076L, 17052029L,
            15897881L, 14837731L, 13860667L, 12957400L,
            12119967L, 11341504L, 10616061L, 9938450L,
            9304124L, 8709072L, 8149737L, 7622945L,
            7125841L, 6655841L, 6210582L, 5787883L,
            5385710L, 5002135L, 4635306L, 4283400L,
            3944578L, 3616914L, 3350049L, 3161693L,
            2980075L, 2804441L, 2634073L, 2468273L,
            2306356L, 2147629L, 1991373L, 1836815L,
            1683094L, 1529196L, 1373866L, 1215430L,
            1051471L, 878080L, 687828L, 461757L,
            0L,
        ),
    ),
    Species.Argon to Dome(
        negLogSaturationPressure = longArrayOf(
            Long.MAX_VALUE, 388506914L, 190822549L, 124927760L,
            91980366L, 72211930L, 59032972L, 49619431L,
            42559275L, 37068043L, 32675057L, 29080795L,
            26085578L, 23551163L, 21378807L, 19496099L,
            17848729L, 16395168L, 15103113L, 13947064L,
            12906620L, 11965266L, 11109490L, 10328128L,
            9611881L, 8952933L, 8344673L, 7781470L,
            7258495L, 6771588L, 6317141L, 5892014L,
            5493456L, 5119054L, 4766676L, 4434433L,
            4137936L, 3882750L, 3641670L, 3413503L,
            3197180L, 2991740L, 2796321L, 2610144L,
            2432504L, 2262766L, 2100353L, 1944738L,
            1795446L, 1652041L, 1514124L, 1381333L,
            1253333L, 1129818L, 1010506L, 895138L,
            783474L, 675292L, 570388L, 468570L,
            369662L, 273500L, 179929L, 88807L,
            0L,
        ),
        liquidDensity = longArrayOf(
            318128604L, 318128604L, 318128604L, 318128604L,
            318128604L, 318128604L, 318128604L, 318128604L,
            318128604L, 318128604L, 318128604L, 318128604L,
            318128604L, 318128604L, 318128604L, 318128604L,
            318128604L, 318128604L, 318128604L, 318128604L,
            318128604L, 318128604L, 318128604L, 318128604L,
            318128604L, 318128604L, 318128604L, 318128604L,
            318128604L, 318128604L, 318128604L, 318128604L,
            318128604L, 318128604L, 318128604L, 318128604L,
            318128604L, 314716591L, 311197164L, 307564652L,
            303812887L, 299935136L, 295924028L, 291771458L,
            287468475L, 283005145L, 278370379L, 273551727L,
            268535107L, 263304473L, 257841364L, 252124336L,
            246128169L, 239822800L, 233171799L, 226130161L,
            218640957L, 210630071L, 201997403L, 192601165L,
            182227088L, 170519710L, 156795281L, 139310717L,
            100000000L,
        ),
        negLogVapourDensity = longArrayOf(
            Long.MAX_VALUE, 385527632L, 188536414L, 123047091L,
            90387379L, 70842086L, 57845450L, 48586059L,
            41659435L, 36285985L, 31998360L, 28499409L,
            25591203L, 23136830L, 21038583L, 19224867L,
            17642036L, 16249099L, 15014201L, 13912215L,
            12923055L, 12030472L, 11221176L, 10484195L,
            9810381L, 9192048L, 8622683L, 8096727L,
            7609402L, 7156571L, 6734634L, 6340432L,
            5971184L, 5624422L, 5297946L, 4989784L,
            4715917L, 4482399L, 4261457L, 4051889L,
            3852611L, 3662647L, 3481111L, 3307197L,
            3140171L, 2979353L, 2824117L, 2673877L,
            2528081L, 2386202L, 2247730L, 2112162L,
            1978994L, 1847704L, 1717739L, 1588489L,
            1459258L, 1329207L, 1197272L, 1062013L,
            921318L, 771733L, 606644L, 409101L,
            0L,
        ),
    ),
)

/** [DOMES] by ordinal, because this is read inside the pressure sweep. */
private val DOME_OF: Array<Dome?> = arrayOfNulls<Dome>(Species.COUNT).also {
    for ((species, dome) in DOMES) it[species.ordinal] = dome
}

/**
 * Peng-Robinson's `α(Tr)` for [species], in [SCALE] — the temperature dependence of the attraction
 * term, and the only place the acentric factor enters the equation of state.
 *
 * `α = [1 + κ(1 − √Tr)]²`, with κ a per-species constant derived once from the acentric factor.
 *
 * ⛔ **Clamped at zero where the bracket would go negative.** Past `√Tr = 1 + 1/κ` the bracket
 * changes sign and squaring sends α *back up*, which is the well-known defect of this α function at
 * high temperature: attraction is supposed to vanish as a fluid gets hot, not return. For water that
 * turn is at about 2,980 K — reachable in a thruster bell and nowhere else — and letting it happen
 * would make a very hot gas start behaving as though it were sticky.
 *
 * ⚠️ **One integer square root per call**, which is why this is a function and not a table. A table
 * would have to span every reduced temperature the game reaches, and most of the vessel's gas is
 * *supercritical* — nitrogen at room temperature is at `Tr = 2.3` — so the interesting range is not
 * the `0..1` the dome tables cover. About 1,800 calls a tick on a 34×43 grid, which is well under a
 * percent of a core. If that ever matters, √Tr factors as `√T / √Tc` and √Tc is a per-species
 * constant that could be computed once.
 */
internal fun alphaAt(temperatureR: Long, species: Species): Long {
    val kappa = CRITICAL[species]?.kappa ?: return SCALE
    if (temperatureR <= 0L) {
        val cold = SCALE + kappa
        return cold * cold / SCALE
    }
    val rootTr = isqrt(temperatureR * SCALE)
    val bracket = SCALE + kappa * (SCALE - rootTr) / SCALE
    if (bracket <= 0L) return 0L
    return bracket * bracket / SCALE
}

/** Natural logarithms are carried to six decimal places. See [Dome.negLogSaturationPressure]. */
private const val NEG_LOG_SCALE = 1_000_000L

/** `ln 2` in [NEG_LOG_SCALE], for the halving-and-remainder split in [expNeg]. */
private const val LN2 = 693_147L

/**
 * `2^(−j/64)` in [SCALE], for `j` in `0..64`.
 *
 * Shared by every fluid because this is arithmetic and not chemistry. Linear interpolation across a
 * sixty-fourth of an octave is good to about 15 parts per million, two orders below the 0.112% the
 * dome itself carries, so it contributes nothing to the error budget.
 */
private val POW2_NEG = longArrayOf(
        100000000L, 98922801L, 97857206L, 96803090L,
        95760328L, 94728799L, 93708382L, 92698956L,
        91700404L, 90712609L, 89735454L, 88768825L,
        87812608L, 86866692L, 85930965L, 85005318L,
        84089642L, 83183829L, 82287774L, 81401371L,
        80524517L, 79657108L, 78799042L, 77950220L,
        77110541L, 76279908L, 75458221L, 74645386L,
        73841307L, 73045890L, 72259040L, 71480667L,
        70710678L, 69948984L, 69195494L, 68450121L,
        67712777L, 66983376L, 66261832L, 65548061L,
        64841978L, 64143501L, 63452548L, 62769038L,
        62092891L, 61424027L, 60762368L, 60107837L,
        59460356L, 58819850L, 58186243L, 57559461L,
        56939432L, 56326081L, 55719337L, 55119129L,
        54525387L, 53938040L, 53357020L, 52782259L,
        52213689L, 51651244L, 51094857L, 50544464L,
        50000000L,
)

/**
 * `exp(−x / NEG_LOG_SCALE)`, in [SCALE] — the way back out of log space.
 *
 * Split into whole halvings and a remainder: `exp(−x) = 2^-n · 2^-f`, where the first is a shift and
 * the second is one lookup in [POW2_NEG]. No division by a variable, no floating point, and the
 * result is exact at the knots.
 *
 * ⚠️ **Guarded above forty halvings** rather than left to `shr`, which in Kotlin takes its count
 * modulo 64 and would turn a very small pressure into a very large one. Forty halvings is `1e-12`
 * of critical, far below anything [SCALE] can represent, so the guard costs nothing real.
 */
private fun expNeg(x: Long): Long {
    if (x <= 0L) return SCALE
    val halvings = x / LN2
    if (halvings > 40L) return 0L
    val remainder = x - halvings * LN2
    // `t · 64` in [SCALE], where `t` is how far through the octave the remainder sits.
    val position = remainder * 64L * SCALE / LN2
    val index = (position / SCALE).toInt()
    val fraction = position % SCALE
    val low = POW2_NEG[index]
    val base = low + (POW2_NEG[index + 1] - low) * fraction / SCALE
    return base shr halvings.toInt()
}

/**
 * Where [temperatureR] sits between knots [index] and `index + 1`, in [SCALE] — **measured in
 * `1/Tr`, not in `Tr`**.
 *
 * That is the whole of what makes the logarithmic tables worth having. `ln P` is a straight line in
 * reciprocal temperature and a curve in temperature, so interpolating the log against `Tr` recovers
 * most of the accuracy and interpolating it against `1/Tr` recovers nearly all of it: 0.921% against
 * 0.112% over the cold range, for one division.
 *
 * Rearranged so it never forms `1/Tr` explicitly — that would be a reciprocal of a reciprocal and
 * would throw away most of the precision it was supposed to buy. The algebra reduces to
 * `(i+1)·(64·Tr − i) / (64·Tr)`, and [scaledRatio] takes the fraction before the scale so the
 * numerator cannot run away.
 */
private fun logFraction(index: Int, temperatureR: Long): Long {
    val span = 64L * temperatureR
    return scaledRatio((index + 1L) * (span - index * SCALE), span, SCALE)
}

/**
 * Interpolation into one of the logarithmic branches, returning a value in [SCALE].
 *
 * Returns zero where either knot is out of the solver's reach, which is the honest rendering of a
 * vapour pressure too small for the equation to have solved for at all.
 *
 * ### What it costs, measured
 *
 * - **Saturation pressure: 0.028%**, against 6% when this branch was interpolated linearly. The
 *   figure the test reports is 0.12%, and that is [SCALE] quantisation rather than this function —
 *   at the cold end of the sweep the pressure is around 800 units and one unit of rounding is an
 *   eighth of a percent.
 * - **Vapour density: 0.12%** over the cold range, against 7.0% linear. Its worst case is 7.2% and
 *   sits in the last knot interval before the critical point, where the dome closes as `√(1 − Tr)`
 *   and no evenly-sampled table can follow a cusp. A change of basis does not help that and was
 *   never going to: it is a different defect, and it is the one [sample] documents.
 */
private fun sampleLog(table: LongArray, temperatureR: Long): Long {
    val position = temperatureR * (N - 1)
    val index = (position / SCALE).toInt()
    if (index >= N - 1) return expNeg(table[N - 1])
    // The first interval reaches down to absolute zero, where `1/Tr` has no value and the table has
    // nothing to interpolate from anyway.
    if (index <= 0) return 0L
    val low = table[index]
    val high = table[index + 1]
    if (low == Long.MAX_VALUE || high == Long.MAX_VALUE) return 0L
    return expNeg(low + (high - low) * logFraction(index, temperatureR) / SCALE)
}

/**
 * Linear interpolation into the dome's one non-logarithmic branch at reduced temperature
 * [temperatureR].
 *
 * Linear is enough, but the error is not uniform and it is worth knowing where it lives — all of it
 * is measured by `SaturationTest`, which re-solves the curve rather than trusting these numbers.
 *
 * ⚠️ **Only the liquid branch comes through here.** The other two are exponential and are stored as
 * logarithms — see [sampleLog], which is where their accuracy is discussed. What is left for this
 * one is the branch that is genuinely close to a straight line.
 *
 * - **The liquid density: within 5.1%**, and essentially all of it in the one knot interval below
 *   the critical point — 0.033% everywhere colder than `Tr = 0.9`. The dome closes
 *   as `√(1 − Tr)`, so both branches reach the critical point with infinite slope, and no table
 *   sampled evenly in `Tr` can follow a cusp. Sampling evenly in `√(1 − Tr)` instead would remove
 *   it, at the cost of a square root on this path; not done, because nothing in the vessel runs
 *   near a critical point.
 * Refining [N] moves it with a known exchange rate — the error is second order, so it falls
 * fourfold per doubling — if a use ever needs it to. Changing the *basis* would not: this branch is
 * already in the one it belongs in, which is exactly why the other two are not.
 */
private fun sample(table: LongArray, temperatureR: Long): Long {
    val position = temperatureR * (N - 1)
    val index = (position / SCALE).toInt()
    if (index >= N - 1) return table[N - 1]
    val fraction = position % SCALE
    val low = table[index]
    return low + (table[index + 1] - low) * fraction / SCALE
}

/**
 * The pressure at which liquid and vapour of [species] at reduced temperature [temperatureR] sit in
 * equilibrium — its **vapour pressure**, in [SCALE].
 *
 * This is the boiling curve, and it is the answer to the question the equation of state deliberately
 * refuses to answer directly: a fluid boils where this exceeds the pressure pressing on it. A pot of
 * water on a mountain and the same pot at sea level read the same curve here and boil at different
 * temperatures, because what changed was the other side of the comparison.
 *
 * Null above the critical temperature, where liquid and vapour are not different things and there is
 * nothing to be in equilibrium *between* — and null for a fluid with no dome at all.
 */
fun saturationPressure(temperatureR: Long, species: Species): Long? {
    val dome = DOME_OF[species.ordinal] ?: return null
    return if (temperatureR >= SCALE) null else sampleLog(dome.negLogSaturationPressure, temperatureR)
}

/**
 * Reduced density of the **condensed** phase at [temperatureR] — liquid above the triple point and
 * solid below it — or null above the critical point.
 *
 * ⚠️ **It was `condensedDensity` and the rename is not cosmetic.** Below
 * [Critical.triplePointKelvin] there is no liquid at any pressure, and answering with one is not a
 * labelling mistake: it hands [org.emerge.demo.outofspace.world.diffuseFluid] something that flows
 * where the world has something that does not.
 *
 * The solid branch is a **measured density** ([Species.solidKgPerCubicMetre]) rather than anything
 * the equation of state produces, because a cubic equation has no solid phase to produce it from —
 * see [Critical.solidDensityR]. So the branch steps at the triple point, which is real: matter does
 * change density when it freezes.
 *
 * ⛔ **For water the step goes the wrong way**, and it is worth knowing before it reads as a bug.
 * Ice really is *less* dense than liquid water — that anomaly is most of why water is interesting —
 * and here it comes out denser, because Peng-Robinson puts liquid water at the triple point around
 * 890 kg/m³ against a real 1000 while the ice branch is the measured 917. It is the equation's
 * liquid-density deficit showing through, not a claim about ice.
 */
fun condensedDensity(temperatureR: Long, species: Species): Long? {
    val c = CRITICAL[species] ?: return null
    if (temperatureR >= SCALE) return null
    if (temperatureR < c.triplePointR) return c.solidDensityR
    val dome = DOME_OF[species.ordinal] ?: return null
    return sample(dome.liquidDensity, temperatureR)
}

/** Reduced density of saturated vapour at [temperatureR], or null above the critical point. */
fun saturatedVapourDensity(temperatureR: Long, species: Species): Long? {
    val dome = DOME_OF[species.ordinal] ?: return null
    return if (temperatureR >= SCALE) null else sampleLog(dome.negLogVapourDensity, temperatureR)
}

/**
 * What fraction of a cell's volume is liquid, in [SCALE], for a cell inside the saturation dome —
 * the **lever rule**.
 *
 * A cell at mean density `ρ` between the two branches holds liquid at `ρl` and vapour at `ρv` in
 * whatever proportion averages to `ρ`, which fixes the split with no freedom left over:
 * `f = (ρ − ρv) / (ρl − ρv)`. Zero at the vapour branch, one at the liquid branch, and sweeping from
 * one to the other *is* boiling — a cell does not jump between phases, it crosses the dome, and how
 * far across it has got is this number.
 *
 * Returns 0 below the dome, [SCALE] above it, and null above the critical temperature.
 */
fun condensedFraction(densityR: Long, temperatureR: Long, species: Species): Long? {
    val vapour = saturatedVapourDensity(temperatureR, species) ?: return null
    val liquid = condensedDensity(temperatureR, species) ?: return null
    if (densityR <= vapour) return 0L
    if (densityR >= liquid) return SCALE
    return (densityR - vapour) * SCALE / (liquid - vapour)
}

/**
 * How much of a cell [species] fills as *liquid*, in [SCALE] — the share of the room that is taken
 * and is no longer available to anything else.
 *
 * **A liquid displaces the gas above it, and until this existed nothing here said so.** Every
 * species shared the whole cell, so a pool of water contributed its vapour pressure *on top of* an
 * undisturbed atmosphere of nitrogen, which put the tile holding it at 1.66 atm against neighbours
 * at 1.00 and blew it apart within a handful of ticks — mass conserved, no instability, the pool
 * simply pushed itself across the room. That looked like the stiffness problem returning and is
 * something else entirely: a pool cannot sit still until the nitrogen has somewhere to not be.
 *
 * Returns 0 for a species that is not condensing.
 */
fun condensedVolumeFraction(mass: Long, species: Species, volume: Int, full: Int, kelvin: Int): Long {
    val densityR = reducedDensity(mass, species, volume, full) ?: return 0L
    val temperatureR = reducedTemperature(kelvin, species) ?: return 0L
    return condensedFraction(densityR, temperatureR, species) ?: 0L
}

/**
 * How many of a cell's [mass] of [species] are present as **vapour** — the rest being liquid.
 *
 * The lever rule again, read as a mass rather than as a volume: the cell holds `1 − f` of its room
 * at [saturatedVapourDensity], and that volume times that density is this. Returns all of [mass] for
 * a species that is not condensing.
 *
 * This exists because **the two phases are not the same substance as far as transport is
 * concerned.** Fick's law describes a mixture spreading through itself, and a pool sitting under an
 * atmosphere is not a mixture — it is two phases with an interface. Differencing concentration
 * across that interface makes the pool read as an infinitely steep gradient and drift dissolves it,
 * which is measurably what was happening: a saturated pool shed 76% of itself in twenty ticks, and
 * excluding its liquid from drift leaves it holding 87%.
 *
 * ⚠️ **Nothing calls this yet**, and the clamp on the last line is why that is worth saying: it read
 * `minOf(mass, mass)` against a `val mass` that shadowed the parameter, so the vapour it reported
 * was never limited by the mass actually present and could exceed it. Harmless while dead;
 * corrected here rather than left for whoever wires up the phase-aware transport it was written for.
 */
fun vapourMass(mass: Long, species: Species, volume: Int, full: Int, kelvin: Int): Long {
    if (mass <= 0L) return mass
    val temperatureR = reducedTemperature(kelvin, species) ?: return mass
    val vapourR = saturatedVapourDensity(temperatureR, species) ?: return mass
    val condensedShare = condensedVolumeFraction(mass, species, volume, full, kelvin)
    if (condensedShare <= 0L) return mass
    // Density × volume, with the fullness applied last so a pipe's eighth of a tile does not round
    // its way to nothing before the density has been divided down — hence the full tile asked for
    // here and the `volume / full` at the end rather than letting the helper do it.
    val fullTile = massAtReducedDensity(vapourR, species, full, full) ?: return mass
    val asVapour = scaledRatio(SCALE - condensedShare, SCALE, fullTile) * volume / full
    return minOf(asVapour, mass)
}
